/*
 * SelectMultiplePrinting.java
 *
 * Created on 30 ¡˝„ÔıÛÙÔÚ 2007, 7:51 Ï
 */
package DirectMail.Tools.ZipCode.Forms;

import DirectMail.Help.Components.Errors;
import DirectMail.Main.MainForm;
import DirectMail.Tools.ZipCode.TKLabels;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.logging.Level;

/**
 *
 * @author  ssoldatos
 */
public class SelectLabelQuantities extends javax.swing.JFrame {

  boolean fromPCADD = false;
  int packMax = 0;
  int sortMin = 0;
  boolean addBarcode;
  boolean infoPost;
  SimpleDateFormat dateFormated;
  String sDate = null;
  private boolean pressPost;
  private boolean elta = true;
  String center;
  final Dimension sDim = new Dimension(403, 220);
  final Dimension eDim = new Dimension(403, 250);
  private String adv;
  private MainForm m;

  /** Creates new form SelectMultiplePrinting
   * @param m 
   */
  public SelectLabelQuantities(MainForm m) {
    this.m = m;
    initComponents();
    setSize(sDim);
    setLocationRelativeTo(null);
    setVisible(true);
    calendarPanel.setVisible(false);
    labelCenter.setVisible(false);
    textFieldCenter.setVisible(false);
  //txtDateChooser = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');


  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    jPanel6 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    calendarPanel = new javax.swing.JPanel();
    txtDateChooser = new datechooser.beans.DateChooserCombo();
    jPanel2 = new javax.swing.JPanel();
    comboAdv = new javax.swing.JComboBox();
    textFieldPackMax = new javax.swing.JTextField();
    textFieldSortMin = new javax.swing.JTextField();
    checkBoxAddBarcode = new javax.swing.JCheckBox();
    jPanel3 = new javax.swing.JPanel();
    textFieldCenter = new javax.swing.JTextField();
    labelsPanel = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    comboPost = new javax.swing.JComboBox();
    labelCenter = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Labeling Quantities");
    setMinimumSize(new java.awt.Dimension(400, 300));
    setResizable(false);

    txtDateChooser.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
    txtDateChooser.setCurrentNavigateIndex(0);
    txtDateChooser.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, comboPost, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}!=0"), txtDateChooser, org.jdesktop.beansbinding.BeanProperty.create("dch_enabled"));
    bindingGroup.addBinding(binding);

    calendarPanel.add(txtDateChooser);

    comboAdv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "–—œ‘≈—¡…œ‘«‘¡ ¡'", "–—œ‘≈—¡…œ‘«‘¡ ¬'", "" }));
    comboAdv.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboAdvActionPerformed(evt);
      }
    });

    textFieldPackMax.setText("50");

    textFieldSortMin.setText("4");

    checkBoxAddBarcode.setToolTipText("Add a barcode below the TK");
    checkBoxAddBarcode.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    checkBoxAddBarcode.setMargin(new java.awt.Insets(0, 0, 0, 0));
    checkBoxAddBarcode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        checkBoxAddBarcodeActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(textFieldSortMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textFieldPackMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(checkBoxAddBarcode)
          .addComponent(comboAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textFieldPackMax, textFieldSortMin});

    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(textFieldSortMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addComponent(textFieldPackMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkBoxAddBarcode)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(comboAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jPanel3.setPreferredSize(new java.awt.Dimension(122, 20));

    textFieldCenter.setText(" ≈Ã–¡");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtDateChooser, org.jdesktop.beansbinding.ELProperty.create("${dch_enabled}"), textFieldCenter, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
    bindingGroup.addBinding(binding);

    textFieldCenter.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textFieldCenterActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(13, Short.MAX_VALUE)
        .addComponent(textFieldCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(textFieldCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(31, Short.MAX_VALUE)
        .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(44, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(86, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(11, 11, 11)
        .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(21, Short.MAX_VALUE))
    );

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Minimum of envelopes in a pack :");

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Add Barcode :");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Maximum of envelopes in a pack :");

    comboPost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "≈À‘¡", "INFOPOST", "PRESSPOST" }));
    comboPost.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboPostActionPerformed(evt);
      }
    });

    labelCenter.setText(" ›ÌÙÒÔ ‰È·ÎÔ„ﬁÚ :");

    jLabel5.setText("–ÒÔÙÂÒ·È¸ÙÁÙ· :");

    javax.swing.GroupLayout labelsPanelLayout = new javax.swing.GroupLayout(labelsPanel);
    labelsPanel.setLayout(labelsPanelLayout);
    labelsPanelLayout.setHorizontalGroup(
      labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(labelCenter, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(comboPost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    labelsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

    labelsPanelLayout.setVerticalGroup(
      labelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(labelsPanelLayout.createSequentialGroup()
        .addComponent(jLabel2)
        .addGap(13, 13, 13)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel4)
        .addGap(11, 11, 11)
        .addComponent(jLabel5)
        .addGap(18, 18, 18)
        .addComponent(comboPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(labelCenter)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Select the quantities for the labeling");

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(okButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(242, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(okButton))
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    bindingGroup.bind();

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-459)/2, (screenSize.height-336)/2, 459, 336);
  }// </editor-fold>//GEN-END:initComponents
  private void checkBoxAddBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAddBarcodeActionPerformed
  }//GEN-LAST:event_checkBoxAddBarcodeActionPerformed

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    addBarcode = checkBoxAddBarcode.isSelected();
    adv = (String) comboAdv.getSelectedItem();
    if (infoPost || pressPost) {
      sDate = txtDateChooser.getText();
      //sDate = dateFormated.format(this.txtDateChooser.getDate());
      center = textFieldCenter.getText();
      System.out.println(sDate);
    }
    try {
      sortMin = Integer.parseInt(textFieldSortMin.getText());
      packMax = Integer.parseInt(textFieldPackMax.getText());
      TKLabels tkl = new TKLabels(sortMin, packMax, addBarcode, elta, infoPost, pressPost, center, sDate, adv, m);
      Thread t = new Thread(tkl);
      t.start();
      dispose();
    } catch (NumberFormatException nFE) {
      Errors.customError("Not a valid number", "The number you entered is not an integer");
      textFieldSortMin.setText("");
      textFieldPackMax.setText("");
    } catch (Exception ex) {
      MainForm.myLog.log(Level.WARNING, null, ex);
    }

  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void comboPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPostActionPerformed
    if (comboPost.getSelectedItem().equals("≈À‘¡")) {
      calendarPanel.setVisible(false);
      labelCenter.setVisible(false);
      textFieldCenter.setVisible(false);
      setSize(sDim);
      elta = true;
      infoPost = false;
      pressPost = false;
      comboAdv.setEnabled(true);
    } else if (comboPost.getSelectedItem().equals("INFOPOST")) {
      calendarPanel.setVisible(true);
      labelCenter.setVisible(true);
      textFieldCenter.setVisible(true);
      setSize(eDim);
      elta = false;
      infoPost = true;
      pressPost = false;
      comboAdv.setEnabled(false);
    } else if (comboPost.getSelectedItem().equals("PRESSPOST")) {
      calendarPanel.setVisible(true);
      labelCenter.setVisible(true);
      textFieldCenter.setVisible(true);
      setSize(eDim);
      elta = false;
      infoPost = false;
      pressPost = true;
      comboAdv.setEnabled(false);
    }
}//GEN-LAST:event_comboPostActionPerformed

  private void textFieldCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCenterActionPerformed
}//GEN-LAST:event_textFieldCenterActionPerformed

  private void comboAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdvActionPerformed
}//GEN-LAST:event_comboAdvActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel calendarPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JCheckBox checkBoxAddBarcode;
  private javax.swing.JComboBox comboAdv;
  private javax.swing.JComboBox comboPost;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JLabel labelCenter;
  private javax.swing.JPanel labelsPanel;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField textFieldCenter;
  private javax.swing.JTextField textFieldPackMax;
  private javax.swing.JTextField textFieldSortMin;
  private datechooser.beans.DateChooserCombo txtDateChooser;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
}
