/*
 * EditUser.java
 *
 * Created on 8 Ιανουάριος 2008, 6:45 πμ
 */
package DirectMail.Users.Forms;

import DirectMail.Main.MainForm;
import soldatos.functions.SwingFunctions;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import soldatos.functions.EncodingFunctions;

/**
 *
 * @author  ssoldatos
 */
public class EditUser extends javax.swing.JFrame implements Runnable {

  private ComboBoxModel usersModel;
  private Vector<String> users = new Vector<String>();

  /** Creates new form EditUser
   * @throws FileNotFoundException
   * @throws IOException 
   */
  public EditUser() throws FileNotFoundException, IOException {
    getUsers();
    initComponents();
  }

  private void editUser(String oldUn, String un, String pass, String type, boolean edit) throws FileNotFoundException, IOException {
    FileReader in = null;
    String buffer = "";
    PrintWriter out = null;

    in = new FileReader("users.dat");
    BufferedReader dis = new BufferedReader(in);
    String line;
    String[] lineArr;
    while ((line = dis.readLine()) != null) {
      lineArr = line.split("\t", -1);
      if (oldUn.equals(lineArr[0])) {
        if (edit) {
          buffer += un + "\t" + EncodingFunctions.base64Encode(pass) + "\t" +
              EncodingFunctions.base64Encode(type + un);
        } else {
        }
      } else {
        buffer += line + "\n";
      }
    }
    in.close();
    out = new PrintWriter(new BufferedWriter(new FileWriter("users.dat")));
    out.print(buffer);
    out.close();

  }

  private int getUserType(String un) throws FileNotFoundException, IOException {
    FileReader in = null;
    
      in = new FileReader("users.dat");
      BufferedReader dis = new BufferedReader(in);
      String line;
      String[] lineArr;
      while ((line = dis.readLine()) != null) {
        lineArr = line.split("\t", -1);
        if (un.equals(lineArr[0])) {
          if (lineArr[2].equals(EncodingFunctions.base64Encode("admin" + un))) {
            return 2;
          } else if (lineArr[2].equals(EncodingFunctions.base64Encode("enveloper" + un))) {
            return 0;
          } else if (lineArr[2].equals(EncodingFunctions.base64Encode("printer" + un))) {
            return 1;
          }
        }
      }
      in.close();
    
    return -1;
  }

  private void getUsers() throws FileNotFoundException, IOException {
    FileReader in = null;
   
      in = new FileReader("users.dat");
      BufferedReader dis = new BufferedReader(in);
      String line;
      String[] lineArr;
      while ((line = dis.readLine()) != null) {
        lineArr = line.split("\t", -1);
        users.addElement(lineArr[0]);
      }
      usersModel = new DefaultComboBoxModel(users);
   
   
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    jLabel1 = new javax.swing.JLabel();
    comboUsers = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    tf_username = new javax.swing.JTextField();
    tf_password = new javax.swing.JTextField();
    buttonOK = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();
    buttonDelete = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    comboType = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Edit user");

    comboUsers.setModel(usersModel);
    comboUsers.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboUsersActionPerformed(evt);
      }
    });

    jLabel2.setText("User:");

    jLabel3.setText("Username :");

    jLabel4.setText("Password :");

    buttonOK.setText("OK");
    buttonOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonOKActionPerformed(evt);
      }
    });

    buttonCancel.setText("Cancel");
    buttonCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonCancelActionPerformed(evt);
      }
    });

    buttonDelete.setText("Delete User");

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, comboUsers, org.jdesktop.beansbinding.ELProperty.create("${selectedItem != 'admin'}"), buttonDelete, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
    bindingGroup.addBinding(binding);

    buttonDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonDeleteActionPerformed(evt);
      }
    });

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Usertype :");

    comboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enveloper", "Printer", "Administrator" }));
    comboType.setSelectedIndex(2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel3)
              .addComponent(jLabel2)
              .addComponent(jLabel4))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(tf_username, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
              .addComponent(tf_password)
              .addComponent(comboUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(buttonOK)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonCancel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonDelete)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(79, 79, 79))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonCancel, buttonOK});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(comboUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonOK)
          .addComponent(buttonCancel)
          .addComponent(buttonDelete))
        .addContainerGap())
    );

    bindingGroup.bind();

    pack();
  }// </editor-fold>//GEN-END:initComponents
  private void comboUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsersActionPerformed
    try {
      tf_username.setText((String) comboUsers.getSelectedItem());
      int type = getUserType((String) comboUsers.getSelectedItem());
      if (type != -1) {
        comboType.setSelectedIndex(type);
      }
    } catch (Exception ex) {
        MainForm.myLog.log(Level.WARNING, null, ex);
    }
  }//GEN-LAST:event_comboUsersActionPerformed

  private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
    dispose();
  }//GEN-LAST:event_buttonCancelActionPerformed

  private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
    String oldUn = (String) comboUsers.getSelectedItem();
    String un = tf_username.getText().trim();
    String pass = tf_password.getText().trim();
    String cType = (String) comboType.getSelectedItem();
    String type = "";
    if (cType.equals("Administrator")) {
      type = "admin";
    } else if (cType.equals("Enveloper")) {
      type = "enveloper";
    } else if (cType.equals("Printer")) {
      type = "printer";
    }
    try {
      editUser(oldUn, un, pass, type, true);
    } catch (FileNotFoundException ex) {
      MainForm.myLog.log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
      MainForm.myLog.log(Level.SEVERE, null, ex);
    }
    dispose();
  }//GEN-LAST:event_buttonOKActionPerformed

  private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
    String oldUn = (String) comboUsers.getSelectedItem();
    try {
      editUser(oldUn, "", "", "", false);
    } catch (Exception ex) {
        MainForm.myLog.log(Level.WARNING, null, ex);
    }
    dispose();
  }//GEN-LAST:event_buttonDeleteActionPerformed

  @Override
  public void run() {
    setVisible(true);
    setLocationRelativeTo(null);
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonDelete;
  private javax.swing.JButton buttonOK;
  private javax.swing.JComboBox comboType;
  private javax.swing.JComboBox comboUsers;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JTextField tf_password;
  private javax.swing.JTextField tf_username;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
}
