/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HeaderJPanel.java
 *
 * Created on 6 Ìבס 2009, 12:56:59 לל
 */
package DirectMail.Help.Components;

import DirectMail.Main.MainForm;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import soldatos.lookaandfeel.Skin;

/**
 *
 * @author ssoldatos
 */
public class HeaderJPanel extends javax.swing.JPanel {

  private MainForm m;
  private int field;

  /** Creates new form HeaderJPanel */
  public HeaderJPanel() {
  }

  HeaderJPanel(MainForm m, String title, int field) {
    this.m = m;
    this.field = field;
    initComponents();
    try {
      label.setText(m.getHeaderTitles().get(field));
      if(MainForm.isColumnFiltered(field) != null){
        label.setForeground(Color.YELLOW);
        label.setText("("+label.getText()+")");
      }
    } catch (ArrayIndexOutOfBoundsException ex) {
      MainForm.myLog.log(Level.WARNING, null, ex);
    }

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    button = new javax.swing.JButton();
    label = new javax.swing.JTextField();

    setBackground(Skin.getColor_5());
    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    setMaximumSize(new java.awt.Dimension(32767, 20));
    setMinimumSize(new java.awt.Dimension(1, 20));
    setPreferredSize(new java.awt.Dimension(153, 20));

    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DirectMail/Images/header_delete.png"))); // NOI18N
    button.setBorder(null);
    button.setMaximumSize(new java.awt.Dimension(18, 18));
    button.setMinimumSize(new java.awt.Dimension(18, 18));
    button.setOpaque(false);
    button.setPreferredSize(new java.awt.Dimension(18, 18));

    label.setBackground(Skin.getColor_5());
    label.setFont(label.getFont().deriveFont(label.getFont().getStyle() | java.awt.Font.BOLD, label.getFont().getSize()-2));
    label.setForeground(Skin.getColor_1());
    label.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    label.setText("jTextField1");
    label.setAlignmentY(0.0F);
    label.setBorder(null);
    label.setOpaque(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(68, 68, 68))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
          .addComponent(button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button;
  private javax.swing.JTextField label;
  // End of variables declaration//GEN-END:variables
}
