/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * replaceFromDbForm.java
 *
 * Created on 28 …бн 2010, 10:05:39 рм
 */
package DirectMail.Tools.Column.Forms;

import DirectMail.Help.Components.MyDraggable;
import DirectMail.Main.MainForm;
import DirectMail.Options.DmOptions;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import soldatos.connection.MyDBCConnection;

/**
 *
 * @author ssoldatos
 */
public class replaceFromDbForm extends MyDraggable {

  private MainForm m;
  private ComboBoxModel modelDb = new DefaultComboBoxModel();
  private ComboBoxModel modelTables = new DefaultComboBoxModel();
  private ComboBoxModel modelJoinedFields = new DefaultComboBoxModel();
  private ComboBoxModel modelValues = new DefaultComboBoxModel();
  private Statement stmt;
  public String database;
  public String table;
  public String joinnedField;
  public String valueField;
  public String notFoundValue;
  public boolean createNewField;
  public boolean cancel;

  public replaceFromDbForm(MainForm m) {
    try {
      this.m = m;
      MyDBCConnection.connect(MainForm.options.toString(DmOptions.HOST),
          MainForm.options.toString(DmOptions.DATABASE),
          MainForm.options.toString(DmOptions.DB_USER),
          MainForm.options.toString(DmOptions.DB_PASSWORD));
      stmt = MyDBCConnection.myConnection.createStatement();
      getDbs();
      initComponents();
      getTables();
      getFields();
      setLocationRelativeTo(null);
      setVisible(true);
    } catch (SQLException ex) {
      MainForm.myLog.log(Level.SEVERE, null, ex);
    }

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    button_ok = new javax.swing.JButton();
    button_cancel = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    combo_db = new javax.swing.JComboBox();
    combo_table = new javax.swing.JComboBox();
    combo_joinedField = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    combo_value = new javax.swing.JComboBox();
    jPanel2 = new javax.swing.JPanel();
    radio_blank = new javax.swing.JRadioButton();
    radio_original = new javax.swing.JRadioButton();
    radio_custom = new javax.swing.JRadioButton();
    textfield_custom = new javax.swing.JTextField();
    checkbox_newField = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Replace field values from Db field");

    button_ok.setText("OK");
    button_ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_okActionPerformed(evt);
      }
    });

    button_cancel.setText("Cancel");
    button_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_cancelActionPerformed(evt);
      }
    });

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Database :");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Table :");

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Joinned Field :");

    combo_db.setModel(modelDb);
    combo_db.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        combo_dbActionPerformed(evt);
      }
    });

    combo_table.setModel(modelTables);
    combo_table.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        combo_tableActionPerformed(evt);
      }
    });

    combo_joinedField.setModel(modelJoinedFields);

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Value Field :");

    combo_value.setModel(modelJoinedFields);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("If no value found"));

    buttonGroup1.add(radio_blank);
    radio_blank.setSelected(true);
    radio_blank.setText("return blank");
    radio_blank.setOpaque(false);

    buttonGroup1.add(radio_original);
    radio_original.setText("return original value");
    radio_original.setOpaque(false);

    buttonGroup1.add(radio_custom);
    radio_custom.setText("return this value");
    radio_custom.setOpaque(false);

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radio_custom, org.jdesktop.beansbinding.ELProperty.create("${selected}"), textfield_custom, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(radio_blank)
          .addComponent(radio_original)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(radio_custom)
            .addGap(18, 18, 18)
            .addComponent(textfield_custom, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(47, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(radio_blank)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(radio_original)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radio_custom)
          .addComponent(textfield_custom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    checkbox_newField.setText("Create new field");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(combo_value, 0, 201, Short.MAX_VALUE)
                  .addComponent(combo_joinedField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(combo_table, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(combo_db, 0, 252, Short.MAX_VALUE))))))
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(button_ok)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_cancel))
          .addComponent(checkbox_newField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(11, 11, 11)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(combo_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(4, 4, 4)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(combo_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(combo_joinedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(combo_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(checkbox_newField)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(button_ok)
          .addComponent(button_cancel))
        .addGap(24, 24, 24))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    bindingGroup.bind();

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
      cancel = true;
      dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
      database = String.valueOf(combo_db.getSelectedItem());
      table = String.valueOf(combo_table.getSelectedItem());
      joinnedField = String.valueOf(combo_joinedField.getSelectedItem());
      valueField = String.valueOf(combo_value.getSelectedItem());
      if(radio_blank.isSelected()){
        notFoundValue = "";
      } else if(radio_original.isSelected()){
        notFoundValue = "original";
      } else if(radio_custom.isSelected()){
        notFoundValue = textfield_custom.getText().trim();
      }
      createNewField = checkbox_newField.isSelected();
      dispose();
    }//GEN-LAST:event_button_okActionPerformed

    private void combo_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tableActionPerformed
    try {
      getFields();
    } catch (SQLException ex) {
      MainForm.myLog.log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_combo_tableActionPerformed

    private void combo_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dbActionPerformed
     try {
      getTables();
    } catch (SQLException ex) {
      MainForm.myLog.log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_combo_dbActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton button_cancel;
  private javax.swing.JButton button_ok;
  private javax.swing.JCheckBox checkbox_newField;
  private javax.swing.JComboBox combo_db;
  private javax.swing.JComboBox combo_joinedField;
  private javax.swing.JComboBox combo_table;
  private javax.swing.JComboBox combo_value;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JRadioButton radio_blank;
  private javax.swing.JRadioButton radio_custom;
  private javax.swing.JRadioButton radio_original;
  private javax.swing.JTextField textfield_custom;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables

  private void getDbs() throws SQLException {
    String sql = "SHOW DATABASES";
    ResultSet rs = stmt.executeQuery(sql);
    Vector<String> dbs = new Vector<String>();
    while (rs.next()) {
      String db = rs.getString(1);
      if (!db.equals("information_schema") && !db.equals("mysql")) {
        dbs.add(db);
      }
    }
    modelDb = new DefaultComboBoxModel(dbs);
  }

  private void getTables() throws SQLException {
    String sql = "SHOW TABLES IN " + String.valueOf(combo_db.getSelectedItem());
    ResultSet rs = stmt.executeQuery(sql);
    Vector<String> tables = new Vector<String>();
    while (rs.next()) {
      String curTable = rs.getString(1);

      tables.add(curTable);

    }
    modelTables = new DefaultComboBoxModel(tables);
    combo_table.setModel(modelTables);
  }
  private void getFields() throws SQLException {
    String sql = "SHOW COLUMNS IN " +  String.valueOf(combo_table.getSelectedItem()) +
        " FROM " + String.valueOf(combo_db.getSelectedItem());
    ResultSet rs = stmt.executeQuery(sql);
    Vector<String> fields = new Vector<String>();
    while (rs.next()) {
      String field = rs.getString(1);
      fields.add(field);
    }
    modelJoinedFields = new DefaultComboBoxModel(fields);
    modelValues = new DefaultComboBoxModel(fields);
    combo_joinedField.setModel(modelJoinedFields);
    combo_value.setModel(modelValues);
  }
}
