/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateCodelinePanel.java
 *
 * Created on 2 Ìבס 2009, 11:14:53 נל
 */
package DirectMail.Tools.Column.Forms;

import DirectMail.Help.Components.FieldsDropDown;
import DirectMail.Help.Components.MyDraggable;
import DirectMail.Help.Functions.DmFunctions;
import DirectMail.Main.MainForm;
import DirectMail.Tools.Column.CreateCodeline;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JTextField;
import soldatos.exceptions.InvalidNumberException;

/**
 *
 * @author ssoldatos
 */
public class CreateCodelinePanel extends MyDraggable {

  private MainForm m;
  public boolean cancel;

  /** Creates new form CreateCodelinePanel */
  private CreateCodelinePanel() {
  }

  public CreateCodelinePanel(MainForm m) {
    this.m = m;
    MainForm.glassPane.activate(null);
    initComponents();
    setModal(true);
    setLocationRelativeTo(null);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    o_mo = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    button_ok = new javax.swing.JButton();
    button_cancel = new javax.swing.JButton();
    radio_mo = new javax.swing.JRadioButton();
    radio_o = new javax.swing.JRadioButton();
    jLabel2 = new javax.swing.JLabel();
    combo_customerCode = new FieldsDropDown(m);
    jLabel3 = new javax.swing.JLabel();
    textfield_addBefore = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    textfield_addAfter = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    combo_amount = new FieldsDropDown(m);
    jLabel6 = new javax.swing.JLabel();
    textfield_eltaAccount = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    combo_type = new javax.swing.JComboBox();
    jLabel8 = new javax.swing.JLabel();
    checkBox_padCustomerCode = new javax.swing.JCheckBox();
    combo_customerPadString = new javax.swing.JComboBox();
    jLabel9 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Create Codeline");

    button_ok.setText("OK");
    button_ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_okActionPerformed(evt);
      }
    });

    button_cancel.setText("Cancel");
    button_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_cancelActionPerformed(evt);
      }
    });

    o_mo.add(radio_mo);
    radio_mo.setSelected(true);
    radio_mo.setText("MO");
    radio_mo.setOpaque(false);

    o_mo.add(radio_o);
    radio_o.setText("O");
    radio_o.setOpaque(false);

    jLabel2.setText("CustomerCode:");

    jLabel3.setText("Add before:");

    textfield_addBefore.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        textfield_addBeforeKeyReleased(evt);
      }
    });

    jLabel4.setText("Add after:");

    textfield_addAfter.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        textfield_addAfterKeyReleased(evt);
      }
    });

    jLabel5.setText("Amount:");

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radio_o, org.jdesktop.beansbinding.ELProperty.create("${selected}"), combo_amount, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
    bindingGroup.addBinding(binding);

    jLabel6.setText("Elta Account:");

    textfield_eltaAccount.setText(" ");

    jLabel7.setText("Type:");

    combo_type.setEditable(true);
    combo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "24" }));

    jLabel8.setText("Pad Customer Code:");

    combo_customerPadString.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Space", "0" }));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBox_padCustomerCode, org.jdesktop.beansbinding.ELProperty.create("${selected}"), combo_customerPadString, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
    bindingGroup.addBinding(binding);

    jLabel9.setText("Amount with 2 dec digits (1.234,00 or 123400 or 1234,00 etc)");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(button_ok)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_cancel))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel2)
              .addComponent(radio_mo)
              .addComponent(jLabel5)
              .addComponent(jLabel6)
              .addComponent(jLabel7)
              .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(radio_o)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(textfield_eltaAccount, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(combo_amount, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                  .addComponent(combo_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(checkBox_padCustomerCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_customerPadString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(combo_customerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_addBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(textfield_addAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radio_mo)
          .addComponent(radio_o))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(combo_customerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3)
              .addComponent(textfield_addBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4)
              .addComponent(textfield_addAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel8)
              .addComponent(checkBox_padCustomerCode)))
          .addComponent(combo_customerPadString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(combo_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(textfield_eltaAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(button_ok)
          .addComponent(button_cancel))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    bindingGroup.bind();

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
    cancel = true;
    dispose();
    MainForm.glassPane.deactivate();
}//GEN-LAST:event_button_cancelActionPerformed

  private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
    int amountField;
    int customerCodeField;
    String customerCodeBefore, customerCodeAfter, eltaAccount, type, customerPadString;
    if (radio_o.isSelected()) {
      amountField = combo_amount.getSelectedIndex();
    } else {
      amountField = -1;
    }
    if (checkBox_padCustomerCode.isSelected()) {
      customerPadString = combo_customerPadString.getSelectedIndex() == 0 ? " " : "0";
    } else {
      customerPadString = "";
    }
    customerCodeField = combo_customerCode.getSelectedIndex();
    customerCodeBefore = textfield_addBefore.getText().trim();
    customerCodeAfter = textfield_addAfter.getText().trim();
    String maxCustomerCode = DmFunctions.getLongestField(m, customerCodeField);
    String intCustomerCode = customerCodeBefore + maxCustomerCode + customerCodeAfter;
    if (intCustomerCode.length() > 15) {
      try {
        throw new InvalidNumberException("Code " + customerCodeBefore + maxCustomerCode + customerCodeAfter + " is too long");
      } catch (InvalidNumberException ex) {
        MainForm.myLog.log(Level.SEVERE, ex.getMessage(), ex);
        soldatos.messages.Messages.customError("Long customer code field", "Code " + customerCodeBefore + maxCustomerCode + customerCodeAfter + " is too long");
        return;
      }
    }

    eltaAccount = textfield_eltaAccount.getText().trim();
    if (eltaAccount.trim().equals("")) {
      MainForm.myLog.log(Level.SEVERE, "Elta account could not be empty");
      soldatos.messages.Messages.customError("Empty elta account", "Elta account could not be empty");
      return;
    }
    type = String.valueOf(combo_type.getSelectedItem());
    CreateCodeline c = new CreateCodeline(m, amountField, customerCodeField,
        customerCodeBefore, customerCodeAfter, eltaAccount, type, customerPadString);
    Thread t = new Thread(c);
    t.start();
    dispose();
}//GEN-LAST:event_button_okActionPerformed

  private void textfield_addBeforeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_addBeforeKeyReleased
    stripChars(textfield_addBefore);
  }//GEN-LAST:event_textfield_addBeforeKeyReleased

  private void textfield_addAfterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_addAfterKeyReleased
    stripChars(textfield_addAfter);
  }//GEN-LAST:event_textfield_addAfterKeyReleased

  private void stripChars(JTextField textfield) {
    textfield.setText(textfield.getText().replaceAll("[^0-9]", ""));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button_cancel;
  private javax.swing.JButton button_ok;
  private javax.swing.JCheckBox checkBox_padCustomerCode;
  private javax.swing.JComboBox combo_amount;
  private javax.swing.JComboBox combo_customerCode;
  private javax.swing.JComboBox combo_customerPadString;
  private javax.swing.JComboBox combo_type;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.ButtonGroup o_mo;
  private javax.swing.JRadioButton radio_mo;
  private javax.swing.JRadioButton radio_o;
  private javax.swing.JTextField textfield_addAfter;
  private javax.swing.JTextField textfield_addBefore;
  private javax.swing.JTextField textfield_eltaAccount;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
}
