/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectRegisteredCodes.java
 *
 * Created on 12 Ìבת 2010, 9:35:11 נל
 */
package DirectMail.Tools.Column.Forms;

import DirectMail.Help.Components.MyDraggable;
import DirectMail.Main.MainForm;
import java.util.logging.Level;
import com.googlecode.svalidators.exceptions.AttributeException;
import com.googlecode.svalidators.formcomponents.ValidationGroup;
import com.googlecode.svalidators.validators.CompareValidator;
import com.googlecode.svalidators.validators.LengthValidator;
import com.googlecode.svalidators.validators.PositiveNumberValidator;
import com.googlecode.svalidators.validators.RequiredValidator;

/**
 *
 * @author scom.googlecode.svalidators
 */
public class SelectRegisteredCodes extends MyDraggable {

  public static int FILE = 0;
  public static int NUMBERS = 1;
  public static int CANCEL = 2;
  public int way;
  private LengthValidator lengthVal;
  public long from;
  public long to;
  public String suffix = "RE", prefix = "GR";
  private CompareValidator compare;
  private PositiveNumberValidator positiveValidator;

  /** Creates new form SelectRegisteredCodes */
  public SelectRegisteredCodes() {
    try {
      initComponents();
      addValidators();
      rb_fromfileActionPerformed(null);
      setLocationRelativeTo(null);
      setVisible(true);
    } catch (AttributeException ex) {
      MainForm.myLog.log(Level.SEVERE, null, ex);
    }
  }

  private void addValidators() {
    lengthVal = new LengthValidator();
    lengthVal.setLength(8);
    lengthVal.setAllowEmpty(false);
    tf_from.addValidator(lengthVal);
    tf_to.addValidator(lengthVal);

    positiveValidator = new PositiveNumberValidator("", false, false);
    tf_from.addValidator(positiveValidator);
    tf_to.addValidator(positiveValidator);

    compare = new CompareValidator("", "", CompareValidator.Type.LESS, false);
    tf_from.addValidator(compare);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    tf_from = new com.googlecode.svalidators.formcomponents.STextField(new PositiveNumberValidator());
    tf_to = new com.googlecode.svalidators.formcomponents.STextField(new PositiveNumberValidator());
    button_file = new javax.swing.JButton();
    button_ok = new javax.swing.JButton();
    button_cancel = new javax.swing.JButton();
    rb_fromfile = new javax.swing.JRadioButton();
    rb_numbers = new javax.swing.JRadioButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    combo_prefix = new javax.swing.JComboBox();
    combo_suffix = new com.googlecode.svalidators.formcomponents.SComboBox(new RequiredValidator());

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Select the registered codes");

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("From :");

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("To :");

    tf_from.setEnabled(false);
    tf_from.setPreferredSize(new java.awt.Dimension(2, 20));
    tf_from.validateValue();
    tf_from.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tf_fromKeyReleased(evt);
      }
    });

    tf_to.setEnabled(false);
    tf_to.setPreferredSize(new java.awt.Dimension(2, 20));
    tf_to.validateValue();
    tf_to.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tf_toKeyReleased(evt);
      }
    });

    button_file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DirectMail/Images/open.gif"))); // NOI18N
    button_file.setText("Open File with Codes");
    button_file.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_fileActionPerformed(evt);
      }
    });

    button_ok.setText("OK");
    button_ok.setEnabled(false);
    button_ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_okActionPerformed(evt);
      }
    });

    button_cancel.setText("Cancel");
    button_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_cancelActionPerformed(evt);
      }
    });

    buttonGroup1.add(rb_fromfile);
    rb_fromfile.setSelected(true);
    rb_fromfile.setText("From File");
    rb_fromfile.setOpaque(false);
    rb_fromfile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rb_fromfileActionPerformed(evt);
      }
    });

    buttonGroup1.add(rb_numbers);
    rb_numbers.setText("By numbers");
    rb_numbers.setOpaque(false);
    rb_numbers.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rb_numbersActionPerformed(evt);
      }
    });

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Prefix :");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Suffix :");

    combo_prefix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RE", "IN", "CD", "CP" }));

    combo_suffix.setEditable(true);
    combo_suffix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GR" }));
    combo_suffix.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        combo_suffixKeyReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(button_ok)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(button_cancel)
        .addContainerGap(254, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(56, 56, 56)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel2)
          .addComponent(jLabel3)
          .addComponent(jLabel5)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(combo_suffix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(combo_prefix, 0, 132, Short.MAX_VALUE)
          .addComponent(tf_from, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tf_to, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(rb_numbers))
        .addContainerGap(155, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(95, 95, 95)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(button_file)
          .addComponent(rb_fromfile))
        .addContainerGap(130, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(17, 17, 17)
        .addComponent(rb_fromfile)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(button_file)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        .addComponent(rb_numbers)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(combo_prefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(combo_suffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(tf_from, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(tf_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(button_ok)
          .addComponent(button_cancel))
        .addContainerGap())
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tf_from, tf_to});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void button_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fileActionPerformed
      way = FILE;
      dispose();
    }//GEN-LAST:event_button_fileActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
      way = CANCEL;
      dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void rb_fromfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_fromfileActionPerformed
      button_file.setEnabled(true);
      tf_from.setEnabled(false);
      tf_to.setEnabled(false);
      tf_from.getValidatorsList().clearValidators();
      tf_to.getValidatorsList().clearValidators();
      button_ok.setEnabled(false);
      tf_from.validateValue();
      tf_to.validateValue();
    }//GEN-LAST:event_rb_fromfileActionPerformed

    private void rb_numbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_numbersActionPerformed
      button_file.setEnabled(false);
      tf_from.setEnabled(true);
      tf_to.setEnabled(true);
      addValidators();
      button_ok.setEnabled(true);
      tf_from.validateValue();
      tf_to.validateValue();
    }//GEN-LAST:event_rb_numbersActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
      ValidationGroup group = new ValidationGroup();
      group.addComponent(tf_from);
      group.addComponent(tf_to);
      group.addComponent(combo_suffix);
      if (!group.validate()) {
        group.errorMessage();
        return;
      }
      way = NUMBERS;
      from = Long.parseLong(tf_from.getText());
      to = Long.parseLong(tf_to.getText());
      prefix = combo_prefix.getSelectedItem().toString();
       suffix = combo_suffix.getSelectedItem().toString();
      dispose();
    }//GEN-LAST:event_button_okActionPerformed

    private void tf_fromKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_fromKeyReleased
      compare.setValueToCompareWith(tf_to.getText().trim());
      tf_from.addValidator(compare);
      tf_from.validateValue();
      tf_to.validateValue();
    }//GEN-LAST:event_tf_fromKeyReleased

    private void tf_toKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_toKeyReleased
      tf_fromKeyReleased(evt);
    }//GEN-LAST:event_tf_toKeyReleased

    private void combo_suffixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_suffixKeyReleased
      suffix = combo_suffix.getSelectedItem().toString();
    }//GEN-LAST:event_combo_suffixKeyReleased

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton button_cancel;
  private javax.swing.JButton button_file;
  private javax.swing.JButton button_ok;
  private javax.swing.JComboBox combo_prefix;
  private com.googlecode.svalidators.formcomponents.SComboBox combo_suffix;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JRadioButton rb_fromfile;
  private javax.swing.JRadioButton rb_numbers;
  private com.googlecode.svalidators.formcomponents.STextField tf_from;
  private com.googlecode.svalidators.formcomponents.STextField tf_to;
  // End of variables declaration//GEN-END:variables
}
