/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AskForSplitNames.java
 *
 * Created on 24 Αυγ 2009, 1:02:12 μμ
 */
package DirectMail.Tools.Addressing.Forms;

import DirectMail.Help.Components.MyDraggable;
import javax.swing.JCheckBox;
import soldatos.functions.ArrayFunctions;

/**
 *
 * @author ssoldatos
 */
public class AskForSplitNames extends MyDraggable {

  private final String[] names;
  private JCheckBox[] checks;
  private boolean dontBother;
  private boolean company;

  /** Creates new form AskForSplitNames
   * @param names
   */
  public AskForSplitNames(String[] names) {
    initComponents();
    this.names = names;
    populate();
    setLocationRelativeTo(null);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    button_OK = new javax.swing.JButton();
    button_cancel = new javax.swing.JButton();
    button_exit = new javax.swing.JButton();
    panel_names = new javax.swing.JPanel();
    button_company = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Check the first names or the company words");

    button_OK.setText("OK - Names");
    button_OK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_OKActionPerformed(evt);
      }
    });

    button_cancel.setText("Cancel");
    button_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_cancelActionPerformed(evt);
      }
    });

    button_exit.setText("Don't bother me");
    button_exit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_exitActionPerformed(evt);
      }
    });

    panel_names.setLayout(new java.awt.GridLayout(8, 1));

    button_company.setText("OK - Company");
    button_company.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_companyActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panel_names, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(button_OK)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_company)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_cancel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_exit)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panel_names, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(button_OK)
          .addComponent(button_cancel)
          .addComponent(button_company)
          .addComponent(button_exit))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 406, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
    checks = null;
    dispose();
  }//GEN-LAST:event_button_cancelActionPerformed

  private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
    checks = null;
    dontBother = true;
    dispose();
  }//GEN-LAST:event_button_exitActionPerformed

  private void button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OKActionPerformed
    dispose();
  }//GEN-LAST:event_button_OKActionPerformed

  private void button_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_companyActionPerformed
    company = true;
    dispose();
  }//GEN-LAST:event_button_companyActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button_OK;
  private javax.swing.JButton button_cancel;
  private javax.swing.JButton button_company;
  private javax.swing.JButton button_exit;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel panel_names;
  // End of variables declaration//GEN-END:variables

  private void populate() {
    String n = names[0].equals("") ? names[1] : names[0];
    String[] allNames = n.split(" ");
    checks = new JCheckBox[allNames.length];
    for (int i = 0; i < allNames.length; i++) {
      checks[i] = new JCheckBox(allNames[i]);
      if (!allNames[i].equals("")) {
        panel_names.add(getChecks()[i]);
      }
    }
  }

  /**
   * @return the dontBother
   */
  public boolean isDontBother() {
    return dontBother;
  }

  /**
   * @return the checks
   */
  public JCheckBox[] getChecks() {
    return checks;
  }

  /**
   * @return the company
   */
  public boolean isCompany() {
    return company;
  }
}
