/*
 * Tooltip.java
 *
 * Created on 12 Μάρτιος 2008, 1:06 μμ
 */

package DirectMail.Help.Forms;

import java.awt.Point;

/**
 *
 * @author  ssoldatos
 */
public class Tooltip extends javax.swing.JFrame {
  
  /** Creates new form Tooltip */
  public Tooltip() {
    initComponents();
    setVisible(true);
  }

  Tooltip(Point p, String string) {
    initComponents();
    labelMaxLength.setText(string);
    setLocation(p);
    setVisible(true);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelMaxLength = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setUndecorated(true);

    labelMaxLength.setBackground(new java.awt.Color(255, 255, 255));
    labelMaxLength.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelMaxLength.setText("jLabel1");
    labelMaxLength.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    labelMaxLength.setOpaque(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(labelMaxLength, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(labelMaxLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JLabel labelMaxLength;
  // End of variables declaration//GEN-END:variables
  
}
