/*
 * CreateTemplate.java
 *
 * Created on 23 Ïêôþâñéïò 2007, 10:20 ðì
 */
package DirectMail.Tools.File.Forms;

import DirectMail.Help.Components.MyDraggable;
import DirectMail.Help.Components.Errors;
import DirectMail.Main.MainForm;
import DirectMail.Tools.File.Template;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author  ssoldatos
 */
public class CreateTemplate extends MyDraggable {

  int fieldsLen[];
  int outFieldsLen[];
  private MainForm m;

  /** Creates new form CreateTemplate
   * @param m 
   */
  public CreateTemplate(MainForm m) {
    this.m = m;
    fieldsLen = new int[m.getFields()];
    outFieldsLen = new int[m.getFields()];
    initComponents();
    getFieldsLength();
    createFields();
    setLocationRelativeTo(m);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    fieldsPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    fieldsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Create a new template");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(fieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(okButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
            .addComponent(cancelButton))
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        .addContainerGap())
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(8, 8, 8)
        .addComponent(fieldsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okButton)
          .addComponent(cancelButton))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    String curValue;
    String curName;
    Component[] AllComponents;
    int j = 0;
    try {
      AllComponents = fieldsPanel.getComponents();
      for (int i = 0; i < AllComponents.length; i++) {
        curName = AllComponents[i].getName();
        if (AllComponents[i] instanceof JTextField) {
          JTextField f = new JTextField();
          f = (JTextField) AllComponents[i];
          curValue = f.getText();
          outFieldsLen[j] = Integer.parseInt(curValue);
          j++;
        }
      }
      dispose();
      Template sc = new Template(m, "saveCreated", outFieldsLen);
      Thread t = new Thread(sc);
      t.start();
    } catch (NumberFormatException ex) {
      Errors.customError("Not a Number", "You entered a non valid length at field " + j);
    }
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void createFields() {
    for (int i = 0; i < m.getFields(); i++) {

      String length = String.valueOf(fieldsLen[i]);
      JTextField f = new JTextField(length, 10);
      f.setName("" + i);
      f.setAlignmentX(Component.LEFT_ALIGNMENT);
      f.setMaximumSize(new Dimension(200, 20));
      f.setMinimumSize(new Dimension(200, 20));
      f.setPreferredSize(new Dimension(200, 20));

      JLabel l = new JLabel("Field_" + i);
      l.setName("Field_" + i + ": ");
      l.setAlignmentX(Component.LEFT_ALIGNMENT);
      l.setMaximumSize(new Dimension(40, 20));
      f.setMinimumSize(new Dimension(40, 20));
      f.setPreferredSize(new Dimension(40, 20));

      fieldsPanel.add(l);
      fieldsPanel.add(f);

    }
    fieldsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
    fieldsPanel.revalidate();

  }

  private void getFieldsLength() {
    String fline, flineArr[];

    fline = m.getFirstLine();
    flineArr = fline.split("" + m.getDelimeter(), -1);
    for (int i = 0; i < flineArr.length; i++) {
      fieldsLen[i] = flineArr[i].length();
    }
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JPanel fieldsPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton okButton;
  // End of variables declaration//GEN-END:variables
}
